org.gradle.jvmargs=-Xmx3G
minecraft_version=1.21.1
archives_base_name=mvo76
mod_version=1.0.8-1.21
maven_group=net.pitan76

# https://fabricmc.net/develop/
yarn_mappings=1.21.1+build.3
fabric_loader_version=0.16.14
fabric_api_version=0.116.1+1.21.1

# https://files.minecraftforge.net/
forge_version=1.21-52.1.1

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.176

# https://www.curseforge.com/minecraft/mc-mods/mcpitanlib
mcpitanlib_version=1.21.1:3.3.2
