org.gradle.jvmargs=-Xmx3G
minecraft_version=1.21.5
archives_base_name=mvo76
mod_version=1.0.6-1.21.5
maven_group=net.pitan76

# Fabric API
fabric_version=0.124.0+1.21.5

# https://fabricmc.net/develop/
yarn_mappings=1.21.5+build.1
fabric_loader_version=0.16.14
fabric_api_version=0.110.0+1.21.3

# https://files.minecraftforge.net/
forge_version=1.21.5-55.0.14

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.5.66-beta

# https://www.curseforge.com/minecraft/mc-mods/mcpitanlib
mcpitanlib_version=1.21.5:3.2.8
