modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"
issueTrackerURL = "https://github.com/PTOM76/mod-volume-options/issues"

[[mods]]
modId = "mvo76"
version = "${version}"
displayName = "Mod Sound Volume Options"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/mod-volume-options"
logoFile = "assets/mvo76/logo.png"
authors = "Pitan"
description = '''
Mod Sound Volume Options is a mod that allows the volume of sounds added by mods to be changed for each mod.
'''

[[dependencies.mvo76]]
modId = "neoforge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mvo76]]
modId = "minecraft"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mvo76-common.mixins.json"
